GitHub get
cacastanedal/workshop-api-testing-js pull request #7
Opened 2017-12-16 19:08 UTC by cacastanedal

2017-12-18 11:54 UTC, aperdomob requested changes

2017-12-18 11:54 UTC, aperdomob commented on test/GithubApi.Repositories.test.js
> +  // Before runing the test case "it"
este comentario no es necesario

2017-12-18 11:54 UTC, aperdomob commented on test/GithubApi.Repositories.test.js
> +      // user.repos_url is a hypermedia direction
eliminar este comentario

2017-12-18 11:54 UTC, aperdomob commented on test/GithubApi.Repositories.test.js
> +          // From all repositories select the one with name === repositoryName
Igual este comentario. Clean Code recomienda no comentar código, si necesitas comentar código es porque estas expresando mal tu código

2017-12-19 02:21 UTC, cacastanedal commented
Comentarios eliminados, gracias por el feedback.

2017-12-19 16:33 UTC, aperdomob approved these changes

2017-12-19 19:48 UTC, merged